vich_uploader:
    db_driver: orm

    mappings:
        rooms:
            uri_prefix: /images/rooms
            upload_destination: '/home/jana/git/TSPpHp/Projet2021WEb/agvoy-app/public/images/rooms'
